name: PrisonGang
author: Staartvin
website: http://dev.bukkit.org/server-mods/prisongang/
main: me.staartvin.prisongang.PrisonGang
version: ${project.version}
description: An advanced, yet simple gangs plugin for prisons.
permissions:
    prisongang.create:
        description: Allows a player to create a gang
        default: op
    prisongang.admin.save:
        description: Allows a player to request a manual save
        default: op
    prisongang.admin.remove:
        description: Allows a player to remove a gang forcefully.
        default: op
commands:
    prisongang:
      description: Main command of PrisonGang
      usage: /<command> <arguments>
      aliases: [pg, prisong, pgangs, pgang, pgs, gang, gangs]